name: Create package after push to main.

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        run: |
          docker login --username rsasantos --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/rsasantos/kerma:latest
          docker push ghcr.io/rsasantos/kerma:latest
