name: Create package and deploy to GCP.

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push Docker image
        run: |
          docker login --username rsasantos --password ${{ secrets.GH_PAT }} ghcr.io
          docker build . --tag ghcr.io/rsasantos/kerma:latest
          docker push ghcr.io/rsasantos/kerma:latest
  
  update-vm:
    runs-on: ubuntu-latest
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCE_SA_KEY }}'
          service_account: 'kerma-project-sa@kermanodeg4.iam.gserviceaccount.com'
  
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          version: '>= 363.0.0'
  
      - name: 'Use gcloud CLI to update container'
        run: 'gcloud --quiet beta compute instances update-container kerma-node-g4-vm --zone europe-west3-c --container-image=ghcr.io/rsasantos/kerma:latest'
        
